# Generated by Django 4.1.3 on 2022-11-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_foods_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
