# Generated by Django 4.1.3 on 2022-11-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foods_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('D', 'نوشیدنی'), ('DI', 'شام'), ('L', 'ناهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
