# Generated by Django 4.1.3 on 2022-11-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foods_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('drinks', 'نوشیدنی'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='drinks', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
